### ISSUE TITLE
[JUnit, Refactoring, Clean Code] 객체의 테스트를 위해 다른 객체의 정보까지 알아야할 필요가 없도록 구현하자.  

### ISSUE THREAD

**Issue by yeoseon** [yeoseon/tip-archive#190]
https://github.com/next-step/java-bowling/pull/135#discussion_r411826900 참고  

## 변경 전  

Frame 테스트를 위해 FrameNumber의 생성자까지 알아야하는 필요성이 생김.  
FrameNumber에 미리 생성해둔 변수를 가지고 쓸 수 있도록 변경 필요  

FrameTest
```
    @Test
    @DisplayName("프레임의 첫 투구 점수는 0이상 10 이하여야 한다.")
    void assertFirstFelledPin() {
        FrameNumber frameNumber = new FrameNumber(1);
        Frame frame = NormalFrame.create(frameNumber);

        assertThatIllegalArgumentException().isThrownBy(() -> {
            frame.play(PinCount.create(11));
        }).withMessage(WRONG_FELLED_PIN);
    }
```

## 변경 후  

FrameNumberTest
```
public class FrameNumberTest {
    public static final FrameNumber frameNumber1 = new FrameNumber(1);
    public static final FrameNumber frameNumber9 = new FrameNumber(9);
    public static final FrameNumber frameNumber10 = new FrameNumber(10);
    ....
}
```
FrameTest
```
import static bowling.domain.frame.FrameNumberTest.*;
    ...

    @Test
    @DisplayName("프레임의 첫 투구 점수는 0이상 10 이하여야 한다.")
    void assertFirstFelledPin() {
        Frame frame = NormalFrame.create(frameNumber1);

        assertThatIllegalArgumentException().isThrownBy(() -> {
            frame.play(PinCount.create(11));
        }).withMessage(WRONG_FELLED_PIN);
    }
```

**Comment by Byeongju-Kong** [comment]
혹시 FrameTest의 assertThatIlegalArgumentException의 withMessage의 인자에 들어가는 WRONG_FELLED_PIN은
FrameTest 내부에 선인이 되어있나요? 아니라면 어디에 선언해두신지 알 수 있을까요?

**Comment by yeoseon** [comment]
> 혹시 FrameTest의 assertThatIlegalArgumentException의 withMessage의 인자에 들어가는 WRONG_FELLED_PIN은
> 
> FrameTest 내부에 선인이 되어있나요? 아니라면 어디에 선언해두신지 알 수 있을까요?

안녕하세요 😃 
해당 에러메시지는 테스트 클래스뿐만 아닌 구현 클래스에도 사용되는 메시지이기에 Frame 클래스에 상수로 선언해둔 것을 가져다 쓴 형태입니다!

본 구현에 쓰이는 값을 Test클래스에 이름만 다른 변수로 하나 더 선언하지는 않았습니다. 상수값이 변경되어도 영향없도록 하기 위해서요.

위 예제는 작은 연습용 프로젝트 였지만 프로젝트 크기에 따라 상수를 하나의 클래스로 모아서 빼는 것들 등등도 고려해볼 것 같습니다.

궁금하신 점 답이 잘 되었는지 모르겠네요 😢
부족한 정리글 읽어주셔서 감사합니다 ~!

**Comment by Byeongju-Kong** [comment]
우선 답변 감사합니다! 
그렇다면 프로덕션 코드에 선언해두신 상수 예외메시지는 접근제어가 최소 디폴드로 되어있다는 말씀이군요.

저도 Test 코드의 예외메시지를 어떻게 선언해야 할지 고민하고 있던 중이었거든요..
여러 가지 방안을 생각을 해보고 있는데, 저는 그냥 테스트클래스의 테스트메소드의 지역변수로 두는 것이 제일 좋다고 생각하는데,
의견이 궁금해서 여쭤보아요.

첫째, 프로덕션 코드의 예외메시지를 private이 아닌 것으로 두는 경우

저도 처음엔 이 방식으로 코드를 작성했습니다.
테스트 코드도 물론 중요하지만, 프로덕션 코드의 변수를 private이 아니라 외부에서 접근 가능하게 할 수 있게 하는 이유가 Test라면,
테스트 코드는 프로덕션 코드의 안정성(?)을 위해서 존재하는 것이라고 생각하는데, **테스트 코드를 위해서 접근제어를 private으로 하지 않는건
모순적이라고 생각**합니다.


둘째, 상수를 하나의 클래스로 모아서 빼는 경우

이 방법이 사실 제가 방금까지 구현해둔 방식입니다. 첫째와 마찬가지로 상수의 변경이 일어나도 선언을 한 군데에 해두었기 때문에, 
수정을 한번만 해야한다는 장점이 있습니다.
하지만 **개념적인 관계성(?)의 측면에서 상수는 클래스 내부에서 가지고 있어야 한다고 생각**해요.
'자신이 필요로 하는 값은 자신이 가지고 있는게 맞지 않을까..' 라는 생각입니다.
또한, 상수가 무엇인지 확인하기 위해선 상수가 모여있는 클래스로 이동해야하고요.


셋째, 테스트 메소드의 지역변수로 가지고 있는 경우

저는 이 방법이 가장 좋다고 생각해요. 이뤄지는 테스트가 단위 테스트이기 때문이죠.
테스트 클래스에서 private static final 로 예외메시지를 선언하기에는 어차피 클래스는 한번만 실행되기 때문에 굳이 라고 생각해요.
테스트 클래스에서 private final 로 예외메시지를 선언하기에는 굳이 필요없는 필드라는 생각이 들고요
테스트 메소드에서 예외메시지를 expectedExceptionMessage와 같은 이름으로 선언한다면,
한 예외에 대해서 한 메소드에서 테스트 한다고 가정하면 (이를 위해선 예외를 구체적으로 나눠야겠죠.)
해당 예외메시지는 단위테스트 한번에서만 필요한 것이라는 측면에서, 그리고 예외테스트와 예외메시지가 개념적으로 밀접하다는 점에서
좋다고 생각합니다.

갑자기 댓글을 달아서 이렇게 하는게 미친 사람 같아 보일 수 있는데, 제가 의견을 공유할 사람이 거의 없고, 
의견을 공유하지 않으면 편협해진다고 생각합니다. 이렇게라도 타인과 의견을 공유하고 싶어서 글 적습니다.

저도 공부한지 오래되지 않아서, 제가 말하는 것들 중에 맞지 않는 개념이 있을 수도 있을거예요.
편하게 의견을 공유해주시면 감사하겠습니다.
